## **Classification Algorithms**

Prediction of data which is *not numerical*.

By using confusion matrix, we can eveluate success of classification algorithm.


In [ ]:
import io
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Logistic Regression Algorithm

In [ ]:
# use veriler.txt
uploaded = files.upload()

In [ ]:
data = pd.read_csv(io.BytesIO(uploaded['veriler.txt']))
print("Done")

Done


In [ ]:
# dependent variables
x = data.iloc[:,1:4].values
# independent variables
y = data.iloc[:,4:].values

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size=0.33,
                                                    random_state=0)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(x_train)
# only transform do not learn (no fit!)
X_test = sc.transform(x_test)


from sklearn.linear_model import LogisticRegression

logr = LogisticRegression(random_state=0)
logr.fit(X_train, y_train)

y_prediction = logr.predict(X_test)
print("Prediction values:")
print(y_prediction)
print("Real values:")
print(y_test)

Prediction values:
['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
Real values:
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Confusion Matrix



A confusion matrix's diagon always gives true results. 

Sensitivity = t-pos/(t-pos + f-neg)
True positive recognition rate

Specificity = = t-neg/(t-neg + f-pos)
True negative recognition rate

Precision = = t-post/(t-pos + f-pos)

Accuracy = (sensitivity X pos/(pos + neg)) + (specificity X neg/(pos + neg))

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_prediction)
print(cm)

# accuracy = 1/8 (8 examples, 1 true)
# error rate = 1 - accuracy = 7/8 

[[0 1]
 [7 0]]


# KNN Algorithm (K Nearest Neigboors)

[Bilgisayar Kavramları Explanation](https://bilgisayarkavramlari.com/2008/11/17/knn-k-nearest-neighborhood-en-yakin-k-komsu/)

[KNN Sklearn Documentation](https://scikit-learn.org/stable/modules/neighbors.html)

Uses euclidien distance (like measuring with ruler) for distance. This can create problems because, maybe one of variable is changing more than other for this, there is modified KNN algorithms.

There are different distance metrics like manhattan, minkowski, mahalanobis...

Closer neigboor is important.

RESEARCH: Lazy and eager learning

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1, metric='minkowski')
knn.fit(X_train, y_train)

y_prediction = knn.predict(X_test)
print(y_prediction)
print(y_test)

cm = confusion_matrix(y_test, y_prediction)
print(cm)

# for 5 neigbors and 1 neigbor confusion matrix is:
#   5: [0 1]                   1: [1 0]
#      [6 1]                      [1 6]
# we can see that 1 neigbor is more succesfull than 5 neigbor,
# not always more neigbor is better!

['k' 'k' 'e' 'k' 'e' 'k' 'k' 'k']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]
[[1 0]
 [1 6]]


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


# Support Vector Machine

[SVC Documentation](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html)

In [34]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(X_train, y_train)

y_prediction = svc.predict(X_test)
print(y_prediction)

cm = confusion_matrix(y_test, y_prediction)
print(cm)

['e' 'e' 'e' 'e' 'k' 'e' 'e' 'k']
[[0 1]
 [6 1]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
