# We will use colab function to upload data files

In [ ]:
import io
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
uploaded = files.upload()

In [ ]:
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['veriler.txt']))
# Dataset is now stored in a Pandas Dataframe

In [ ]:
# boykilo = data[['boy', 'kilo']]
# print(boykilo)
print(data)

The code below here fills missing values with mean value of that column

(use eksikveriler.txt here)

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan , strategy='mean')

age = data.iloc[:,1:4].values   # iloc[startrow:endrow, startcolmn:endcolumn]
imputer = imputer.fit(age[:,1:4]) # fit used for learning purposes
age[:,1:4] = imputer.transform(age[:,1:4]) 
print(age)

# fit is for learning, transform for applying

We can't sort some types of data. We can solve this issue by giving a new column to each of them.

In [ ]:
country = data.iloc[:,0:1].values
# print(country)

from sklearn import preprocessing
# le : label encoding
le = preprocessing.LabelEncoder()
country[:,0] = le.fit_transform(data.iloc[:,0])
# print(country)

# ohe : one hat encoding
ohe = preprocessing.OneHotEncoder()
country = ohe.fit_transform(country).toarray()
print(country)

Create results frame using pandas library

In [ ]:
print(len(data))
# using len:
dataLength = len(data)
# create 0 to 22 indexing:
result = pd.DataFrame(data=country, index = range(dataLength),
                      columns = ['fr', 'tr', 'us'])
print(result)

result2 = pd.DataFrame(data = age, index = range(dataLength),
                       columns=['boy', 'kilo', 'yas'])
print(result2)
# -1 to take last column
sex = data.iloc[:,-1].values
result3 = pd.DataFrame(data = sex, index = range(dataLength),
                       columns=['cinsiyet'])

# merge all results together
s = pd.concat([result, result2], axis=1)  # it does concatenation VERTICAL
# if there is NO axis=1
print(s)

s2 = pd.concat([s, result3], axis=1)
print(s2)

Dividing dataset for learning and testing

In [ ]:
from sklearn.model_selection import train_test_split
# x for independent y for dependent variables
# 0.33 mean 33% for test 67% for train so in here 7 for test rest for train
x_train, x_test, y_train, y_test = train_test_split(s, result3, 
                                                    test_size=0.33,
                                                    random_state=0)
# here x includes everything except sex
# y only includes sex because I think we will create a model to
# guess a person's sex using other values

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
# create object from StandarScaler class
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)
print(X_train)

[[-0.63245553  0.8660254  -0.40824829  0.45049444 -0.29657884 -0.26680787]
 [-0.63245553  0.8660254  -0.40824829  1.00824945  0.5096549   0.        ]
 [ 1.58113883 -1.15470054 -0.40824829  1.13696215  0.91277178 -0.17787191]
 [-0.63245553  0.8660254  -0.40824829 -1.6089087  -1.18343596 -1.15616745]
 [-0.63245553  0.8660254  -0.40824829 -1.35148331 -1.34468271 -1.33403936]
 [-0.63245553  0.8660254  -0.40824829  0.57920713  0.91277178  0.44467979]
 [ 1.58113883 -1.15470054 -0.40824829  0.87953676  0.5096549   0.17787191]
 [-0.63245553 -1.15470054  2.44948974  0.79372829  1.51744708  0.71148766]
 [-0.63245553  0.8660254  -0.40824829  0.36468597  0.91277178  0.88935957]
 [ 1.58113883 -1.15470054 -0.40824829  0.70791983  0.8321484   0.26680787]
 [-0.63245553  0.8660254  -0.40824829 -1.43729177 -1.50592946 -1.42297532]
 [-0.63245553  0.8660254  -0.40824829 -1.56600447 -1.50592946 -1.33403936]
 [ 1.58113883 -1.15470054 -0.40824829  0.32178174  0.10653803  1.95659106]
 [-0.63245553 -1.15470054